### ISSUE TITLE
java.lang.RuntimeException: Unable to start service com.gyf.cactus.service.LocalService@fc1b36 with Intent

### ISSUE THREAD

**Issue by daoxiaomianzi123** [gyf-dev/Cactus#65]
小米14
android 14
出现2024-05-10 15:40:21.380 17093-17093/com.gyf.cactus.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gyf.cactus.sample, PID: 17093
    java.lang.RuntimeException: Unable to start service com.gyf.cactus.service.LocalService@fc1b36 with Intent { cmp=com.gyf.cactus.sample/com.gyf.cactus.service.LocalService (has extras) }: java.lang.SecurityException: Unable to start service Intent { cmp=com.gyf.cactus.sample/com.gyf.cactus.service.RemoteService (has extras) }: Unable to launch app com.gyf.cactus.sample/10398 for service Intent { cmp=com.gyf.cactus.sample/com.gyf.cactus.service.RemoteService }: process is bad
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5046)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2418)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:224)
        at android.os.Looper.loop(Looper.java:318)
        at android.app.ActivityThread.main(ActivityThread.java:8677)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
     Caused by: java.lang.SecurityException: Unable to start service Intent { cmp=com.gyf.cactus.sample/com.gyf.cactus.service.RemoteService (has extras) }: Unable to launch app com.gyf.cactus.sample/10398 for service Intent { cmp=com.gyf.cactus.sample/com.gyf.cactus.service.RemoteService }: process is bad
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1954)
        at android.app.ContextImpl.startForegroundService(ContextImpl.java:1917)
        at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:841)
        at com.gyf.cactus.ext.CactusExtKt.startInternService(CactusExt.kt:339)
        at com.gyf.cactus.ext.CactusExtKt.startAndBindService(CactusExt.kt:325)
        at com.gyf.cactus.ext.CactusExtKt.startAndBindService$default(CactusExt.kt:320)
        at com.gyf.cactus.ext.CactusExtKt.startRemoteService(CactusExt.kt:290)
        at com.gyf.cactus.service.LocalService.onStartCommand(LocalService.kt:131)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5028)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2418) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:224) 
        at android.os.Looper.loop(Looper.java:318) 
        at android.app.ActivityThread.main(ActivityThread.java:8677) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by ccchen92** [comment]
+1 我也遇到了，更新到澎湃OS就这样了。之前红米PAD是MIUI时没问题。
